---
- hosts: all
  become: yes

  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: Remove nginx package
      apt:
        name: nginx
        state: absent
        autoremove: yes
